version: "3.8"
services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongodb
    volumes:
      - ./mongo-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:mongodb@mongodb:27017/

  postgres:
    image: postgres:15
    container_name: monew_local_postgres
    environment:
      POSTGRES_USER: hi
      POSTGRES_PASSWORD: hi
      POSTGRES_DB: localmonewdb
    ports:
      - "5432:5432"
    volumes:
      - localmonewdbdata:/var/lib/postgresql/data

volumes:
  localmonewdbdata:
