spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  application:

    name: monew

  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DATABASE}

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql: TRACE
    com.team1.monew.comment.*: DEBUG

aws:
  s3:
    access-key: ${AWS_S3_ACCESS_KEY}
    secret-key: ${AWS_S3_SECRET_KEY}
    region: ${AWS_S3_REGION}
    bucket: ${AWS_S3_BUCKET}

naver:
  client-id: ${NAVER_CLIENT_ID}
  client-secret: ${NAVER_CLIENT_SECRET}
  news-api-url: ${NAVER_API_URL}
  source-name: ${NAVER_SOURCE_NAME}

rss:
  chosun-url: ${CHOSUN_URL}
  chosun-source-name: ${CHOSUN_SOURCE_NAME}