spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    org.springframework.web: INFO
    com.team1.monew.*: INFO

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
  endpoint:
    health:
      show-details: never
  info:
    env:
      enabled: false